slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: false
    localization_mode: true
    map_file_name: ".../sumo_arena.yaml"
    odom_frame: "odom"
    base_frame: "base_link"
    map_frame: "map"
    scan_topic: "/scan"
